export const metadata = { title: "Terms of Service — Wall Street Academy" };

export default function TosPage() {
  return (
    <div
      style={{
        minHeight: "100vh",
        background: "var(--bg)",
        color: "var(--bone)",
        fontFamily: "-apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
      }}
    >
      <div style={{ maxWidth: 760, margin: "0 auto", padding: "64px 32px 120px" }}>
        {/* Header */}
        <div style={{ marginBottom: 48 }}>
          <p style={{ fontSize: 11, fontWeight: 700, letterSpacing: "0.18em", textTransform: "uppercase", color: "var(--acid)", marginBottom: 16 }}>
            Wall Street Academy LLC
          </p>
          <h1 style={{ fontSize: 36, fontWeight: 700, lineHeight: 1.2, margin: "0 0 12px" }}>
            Terms of Service
          </h1>
          <p style={{ fontSize: 14, color: "var(--ash)", margin: 0 }}>
            Effective Date: July 1, 2026 &nbsp;·&nbsp; Last Updated: July 9, 2026
          </p>
        </div>

        {/* Content */}
        <div style={{ lineHeight: 1.8, fontSize: 15, color: "var(--ash)" }}>

          <Section title="1. Agreement to Terms">
            By accessing or using any product, platform, course, community, or service offered by Wall Street Academy LLC ("WSA," "we," "us," or "our"), including but not limited to the Inner Circle program, the CueBanks platform, live sessions, and digital content, you agree to be bound by these Terms of Service. If you do not agree to these terms, do not use our services.
          </Section>

          <Section title="2. Educational Purpose Only">
            All content, analysis, trade ideas, signals, educational materials, and coaching provided by WSA are strictly for educational and informational purposes. Nothing on any WSA platform or communicated by any WSA representative constitutes financial advice, investment advice, trading recommendations, or a solicitation to buy or sell any financial instrument. Trading foreign exchange, futures, stocks, or any other financial instrument involves substantial risk of loss. Past results are not indicative of future performance. You are solely responsible for your own trading decisions.
          </Section>

          <Section title="3. No Guarantee of Results">
            WSA makes no representation or warranty that any student, member, or user will achieve any particular financial outcome as a result of participating in any program, course, or community. Individual results vary based on factors including but not limited to prior experience, time commitment, market conditions, and individual discipline. Any income or trading results shown by WSA, Quillan Black, or any affiliated instructor are not typical and are not a promise or guarantee of results.
          </Section>

          <Section title="4. Eligibility">
            You must be at least 18 years of age and legally capable of entering into a binding contract to use our services. By using our services, you represent and warrant that you meet these requirements.
          </Section>

          <Section title="5. Payment and Refund Policy">
            All program fees are due as stated at the time of enrollment. Payments are non-refundable except as explicitly stated in a separate written agreement or as required by applicable law. If a payment plan is selected, you are responsible for all installments regardless of continued participation. Failure to complete payment may result in suspension or termination of access.
          </Section>

          <Section title="6. Intellectual Property">
            All content on WSA platforms — including course videos, trading frameworks, PDFs, system documents, live session recordings, community posts by WSA staff, and any other materials — is the exclusive intellectual property of Wall Street Academy LLC. You may not reproduce, distribute, sell, sublicense, publicly display, or create derivative works from any WSA content without prior written consent. Sharing login credentials, recordings, or course materials with non-members is strictly prohibited and may result in immediate termination without refund.
          </Section>

          <Section title="7. Community Standards">
            WSA members agree to maintain a standard of professionalism and respect in all community spaces (Discord, chat platforms, live calls, etc.). Prohibited conduct includes but is not limited to: harassment, hate speech, solicitation of other members, sharing of third-party signals or services, and any activity that disrupts the learning environment. WSA reserves the right to remove any member for conduct violations without refund.
          </Section>

          <Section title="8. Cue AI Disclaimer">
            The Cue AI chatbot is an AI-powered educational assistant. Its responses are generated by an artificial intelligence model and do not constitute financial or trading advice. Cue AI may make errors, provide outdated information, or generate responses that are incomplete or inaccurate. Always apply your own judgment and consult qualified professionals before making any financial decisions.
          </Section>

          <Section title="9. Privacy">
            WSA collects personal information including name, email address, and payment information to provide and improve its services. We do not sell your personal information to third parties. By using our services, you consent to collection and use of your information as described in our Privacy Policy (available upon request).
          </Section>

          <Section title="10. Limitation of Liability">
            To the maximum extent permitted by applicable law, WSA and its officers, directors, instructors, affiliates, and agents shall not be liable for any indirect, incidental, special, consequential, or punitive damages, including without limitation lost profits, lost trading capital, or data loss, arising out of or related to your use of our services, even if advised of the possibility of such damages. Our total liability to you for any cause of action shall not exceed the amount you paid to WSA in the three months preceding the claim.
          </Section>

          <Section title="11. Indemnification">
            You agree to indemnify, defend, and hold harmless WSA and its officers, directors, employees, and agents from and against any claims, liabilities, damages, losses, and expenses, including reasonable legal fees, arising out of your use of our services, your violation of these Terms, or your violation of any rights of a third party.
          </Section>

          <Section title="12. Modification of Terms">
            WSA reserves the right to update or modify these Terms at any time. We will notify members of material changes via email or platform notification. Continued use of our services after such notice constitutes acceptance of the updated Terms.
          </Section>

          <Section title="13. Termination">
            WSA may suspend or terminate your access to any service at any time, with or without cause, at its sole discretion. You may terminate your membership by contacting support. Termination does not entitle you to a refund except as otherwise provided in Section 5.
          </Section>

          <Section title="14. Governing Law">
            These Terms shall be governed by and construed in accordance with the laws of the State of Florida, without regard to its conflict of law provisions. Any dispute arising under these Terms shall be resolved by binding arbitration in the State of Florida, except that either party may seek injunctive relief in a court of competent jurisdiction.
          </Section>

          <Section title="15. Contact">
            For questions regarding these Terms, please contact Wall Street Academy LLC at:{" "}
            <a href="mailto:support@wallstreetacademyfx.com" style={{ color: "var(--acid)", textDecoration: "none" }}>
              support@wallstreetacademyfx.com
            </a>
          </Section>

        </div>

        {/* Footer */}
        <div
          style={{
            marginTop: 64,
            paddingTop: 32,
            borderTop: "1px solid var(--line)",
            textAlign: "center",
            fontSize: 12,
            color: "var(--ash)",
          }}
        >
          © {new Date().getFullYear()} Wall Street Academy LLC. All rights reserved.
        </div>
      </div>
    </div>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div style={{ marginBottom: 36 }}>
      <h2
        style={{
          fontSize: 13,
          fontWeight: 700,
          letterSpacing: "0.08em",
          textTransform: "uppercase",
          color: "var(--bone)",
          marginBottom: 10,
        }}
      >
        {title}
      </h2>
      <p style={{ margin: 0 }}>{children}</p>
    </div>
  );
}
